unique_ids:
  forms:
    HomeForm: RXKECMZN34MQAHDRK6EPIICDWR6S3KGX
  modules: {}
  server_modules:
    SaveAndSendEmail: K3BJP54LLIFUNBZKPJQNF3SQ3PXH3K3L
  assets:
    code-button.png: '1695342618749193575253721.17725'
    run-button.png: '1695343459366326673384303.53296'
    standard-page.html: Q3QO6SVCSYGG2URQPHD2WQN53IJYWBMT
    theme.css: WZK5YAI72HXBAVF2NY77323MVSKI5HGU
  scripts: {}
